### ISSUE TITLE
gh-pages?

### ISSUE THREAD

**Issue by shawngraham** [nullism/pykwiki#13]
Hi,
I love this; it solves some problems for me (discussed here http://electricarchaeology.ca/2015/10/06/an-elegant-open-notebook/ ) but I'm kinda falling down at the last hurdle. I thought I could use gh-pages branch as a way of putting pykwiki online, by moving the docroot over. I'm ending up with this: http://shawngraham.github.io/dry-run-pykwiki/  and clearly I've got something misconfigured. I tried changing the base url in config.yaml to point to shawngraham.github.io/dry-run-pykwiki/ but no joy. Wondered if anyone had some suggestions.

Many thanks
S

**Comment by nullism** [comment]
Hey Shawn,

So the "Welcome" link goes to /index.html instead of /dry-run-pykwiki/index.html, and the "Home" link does the same. I don't suppose you have the source of that repository available somewhere, do you? I'd like to take a look at it; very possible there's a bug in the theme itself. 

Sorry about that.

**Comment by nullism** [comment]
Oh! I should also ask what the `web_prefix` setting is. In this case, it should be set to `/dry-run-pykwiki` (no trailing slash). The base_url should **not** need to include a web_prefix (if it only works with it, then I need to fix something, and I apologize if that's the case).

So, to recap:

```
site:
    ....
    base_url: "http://shawngraham.github.io"
web_prefix: "/dry-run-pykwiki"
```

**Comment by shawngraham** [comment]
oh! Thanks, I'll give that a try. Cheers!

**Comment by nullism** [comment]
Hey Shawn, I'm going to go ahead and close this out. Pykwiki 1 really depends on how the particular theme you're using was implemented. I have definitely solved this issue for Pykwiki2 (single theme/SASS enabled), which I plan on releasing this month.
