### ISSUE TITLE
PyKwiki 2 doesn't seem to be compatible with existing PyKwiki 1 content

### ISSUE THREAD

**Issue by phayz** [nullism/pykwiki#16]
Having upgraded to PyKwiki 2 I ran "pykwiki cache -f" over my existing blog and the resulting traceback message was as follows:

```
Could not load /home/rdickens/personal/pywkwiki_OLD_blog/config.yaml, using default settings
========================================
Caching source posts
Traceback (most recent call last):
  File "/usr/bin/pykwiki", line 357, in <module>
    command_cache(args)
  File "/usr/bin/pykwiki", line 206, in command_cache
    num_cached = ctrl.cache_posts(plist, force=force)
  File "/usr/lib/python2.7/site-packages/pykwiki/core.py", line 300, in cache_posts
    pg = Post(pf)
  File "/usr/lib/python2.7/site-packages/pykwiki/core.py", line 769, in __init__
    conf.check()
  File "/usr/lib/python2.7/site-packages/pykwiki/core.py", line 172, in check
    raise Exception('conf.version does not exist')
Exception: conf.version does not exist
```

**Comment by nullism** [comment]
Hey Phayz,

I'm still working on the documentation and have another update to PyKwiki2 coming this week. 

However, pykwiki should support the upgrade command. 

In the project directory, try:

    pykwiki upgrade

**Comment by phayz** [comment]
Thanks for the quick reply.

```pykwiki upgrade``` in the project dierctory worked.  \O/

**Comment by nullism** [comment]
Awesome. I'll make this clear when I finish the Pykwiki2 documentation -- which is probably about a month out.

**Comment by phayz** [comment]
I'm a professional technical writer, so if you need help with PyKwiki2's documentation please ask.

**Comment by nullism** [comment]
I'd love the help, but most of the important knowledge surrounding Pykwiki 2 exists only in my head. If you see anything missing or lacking once I get more content, I'd be very grateful for any commits you make to the repository (`docs/` is a mirror of the documentation). Whatever you do, please continue to provide feedback when you find something broken -- it truly helps improve Pykwiki and motivates me to spend more time on it. Thanks again.

**Comment by phayz** [comment]
Understood. I can only document PykWiki and since all that information is in your head, I'd only be slowing you down.

I'm certainly willing to review the documentation and help where I can do so.

**Comment by wabbajack** [comment]
Hi,
Please read this info, it means so much to me, here is the link <http://lafrophophu.sylviawoodsharpcentre.com/lnpmmqf>

See you around, aaron@level60design.com
