### ISSUE TITLE
[RFE] Provide commands for "build" and "serve" which are easier to type

### ISSUE THREAD

**Issue by phayz** [nullism/pykwiki#18]
I admit this seems like a complaint about nothing, but since the project has a name that is not easy to type, perhaps simpler commands could be added.

For example, "make" might regenerate the site's content and "make serve" might have it hosted locally by Python? I'm taking these examples from another static site generator.

**Comment by nullism** [comment]
Good idea. Do you know the name of the project that uses `make`?  I'd like to take a look at it to see how they're doing that. 

Would something shorter but still unique, like `pk cache`, provide the same benefits as `make serve`?

**Comment by phayz** [comment]
The project I was thinking of is named Urubu - http://urubu.jandecaluwe.com.

I'd be happier if the commands were shorter, but still unique. Of course if you're using PyKwiki on Linux or similar, you could easily set up command-line aliases.
