### ISSUE TITLE
[RFE] Add command which publishes the output to a web host

### ISSUE THREAD

**Issue by phayz** [nullism/pykwiki#19]
It would be great to have the option of having the static content pushed to your preconfigured web host from within PyKwiki. For example, a "git commit" of the content, then "git push" could have the content pushed to GitHub for hosting.

**Comment by nullism** [comment]
I think I can add a git-hook example, or even a builtin hook, to run `pykwiki cache -f` when a git-commit is made. However, I would like to keep actual git functions outside of Pykwiki. I'll keep this open while I think on it. Thanks for the suggestion!

**Comment by phayz** [comment]
I agree that if this feature is added, it should not be exclusive to git, nor GitHub. The aim would be to provide the writer an easy means of publishing the output. Perhaps it could be a configuration item where the writer can specify a "publish" command, whether that uses curl, git or some other tool.

**Comment by nullism** [comment]
That's not a bad idea. Maybe add a `post_cache_script:` config.yaml variable that could point to a script of your choice. Though, it'd be just as easy to write a bash script like:

```bash
#!/bin/bash
# cache.sh
pykwiki cache -f
git add --all
git commit -m "Cached stuff"
git push origin master
```

What do you think?

**Comment by phayz** [comment]
Your example bash script looks good and would achieve precisely what I intended with this request. Perhaps the "publishing" script could be an *optional* configuration item. Taking this approach requires the writer to enable it, allowing the opportunity to present the example script, but make it clear that that is not part of PyKwiki itself.

**Comment by phayz** [comment]
Thinking about this again and I now think that this issue should be closed. There are too many variables that prevent you from reliably providing a "push to host" option. Instead, providing an example bash script would be a good start for someone wanting this feature. I believe that anyone using PyKwiki is also likely to be familiar with at least basic scripting, in which case adapting an example to their needs should be fairly easy.

**Comment by wabbajack** [comment]
Hi,
Have you seen this stuff? I think it's great, lust take a look here <http://frytiteche.foxholem4m.com/lnhjewji>

Good wishes, aaron@level60design.com
