### ISSUE TITLE
PyKwiki's home page does not state what it *is*

### ISSUE THREAD

**Issue by phayz** [nullism/pykwiki#21]
Background: Neither the PyKwiki 2.x or 1.x sites' home pages state just what it is.

Requested enhancement: Add a brief description of PyKwiki.

As an aside, I think the current one-line description on the GitHub page could be improved. It currently states "PyKwiki is a static content generation engine for Python." My suggested version of this would be "PyKwiki is a easy-to-use static site generator especially suited for blogs."

**Comment by phayz** [comment]
Thanks for resolving this. Having a basic description now means visitors to the site know what PyKwiki is in an instant.

**Comment by nullism** [comment]
No problem. Thanks for the suggestion -- it should have been obvious to me.
