### ISSUE TITLE
Change hrefs relatively to current folder

### ISSUE THREAD

**Issue by johannes-z** [nullism/pykwiki#22]
Right now, all the links and assets are linked as such: `/link/to/file`. When serving the wiki under a folder, f.e. `https://example.com/wiki`, all the links break. The `web_prefix` config only helps for assets. `search.html` and `posts.html` still point to `https://example.com/search.html`. The links should be added like this instead: `./link/to/file`.

**Comment by nullism** [comment]
Hi there! 

I may see an issue when clicking a *tag* to take you to search.html. Is that where this is? 

Or are these links in `links.yaml`?

If so, if your site is on `/wiki` and you specify a link as `href: /not-wiki/foo.png` it should *not* behave as a relative link, due to the leading slash. `href` is literally `<a href="[href value]">`.

**Comment by johannes-z** [comment]
So the `Search` link in the topnav is `/search.html` becoming `https://example.com/search.html` instead of `https://example.com/wiki/search.html`.

The `links.yaml` is unchanged, e.g.:

```yaml
- Search:
  post: search
```

My `config.yaml` is set to:

```yaml
base_path: /<path_to_www>/wiki
site:
  base_url: https://example.com/wiki
web_prefix: "/wiki"
```

Without `web_prefix` the styles wouldn't load either. I guess this could be fixed by the webserver configuration, but I couldn't get it to work that way.

**Comment by nullism** [comment]
Thanks for the information. You're correct, post: search should use the web prefix. Could you try `touch links.yaml && pykwiki cache -f` after updating the web_prefix and tell me if that fixes it?

Thanks again for helping troubleshoot.

**Comment by johannes-z** [comment]
Yes, that fixed it!

**Comment by nullism** [comment]
Awesome! I'm going to leave this open with an action item of forcing re-cache if `-f` is specified.
