### ISSUE TITLE
[RFE] Expose 'target_dir' in config.yaml

### ISSUE THREAD

**Issue by troyengel** [nullism/pykwiki#24]
Would you be willing to add `target_dir` to the `config_text_properties[]` array so we can override the default?

I am building via a CI hook on Gitlab to use Pages, the output has to be in a directory "public" for it to get picked up by automation. So I have a `mv docroot public` command in my build yaml - I'd like to just override that cleanly in the config.yaml file. :) I imagine others would find it useful for various reasons.

**Comment by nullism** [comment]
Hi again,

Yeah, exposing properties should be just as simple as adding them to the `config_text_properties` array. If they're not present in the conf, then they won't be overwritten.  This change should be in 2.1.20 when I test it and push the new build (tonight).

Thanks!
